name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Start Cypress tests
        run: npx cypress run -b chrome

      - name: Update README with test results
        run: |
          TEST_OUTPUT=$(npx cypress run --quiet --json | jq '.runStats')
          NUM_TESTS=$(echo $TEST_OUTPUT | jq '.totalTests')
          NUM_FAILURES=$(echo $TEST_OUTPUT | jq '.totalFailed')

          sed -i "s/{num_tests}/$NUM_TESTS/g; s/{num_failures}/$NUM_FAILURES/g" README.md

